version: '3'
services:
    mongo:
        container_name: mongoDB
        image: mongo
        environment: 
            - MONGO_INITDB_DATABASE=sopesDB
        network_mode: "bridge"
        ports:
            - "27017:27017"
    python:
        container_name: serve
        build: 
            context: .
            dockerfile: Dockerfile
        network_mode: "bridge"
        ports:
            - "3000:3000"
        volumes: 
            - "/proc/:/elements/procs/"